export const studios = [
  {
    imgLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: ["40", "25"],
    duration: ["12", "24"],
    courses: ["Zumba", "Yoga", "Body-Pump"],
    wellnes: ["Spa"],
    cardio: ["Rowing", "Stepper"],
    strength: ["Hanteln", "Geräte"],
    ladyarea: "yes",
    kidsarea: "yes",
    neighbourhood: "Ehrenfeld",
    adress: "Venloer Str. 389, 50825 Köln",
    website: {},
    imgLocation: ""
  },
  {
    imgLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: [],
    duration: "",
    courses: {},
    wellnes: {},
    cardio: {},
    strength: {},
    ladyarea: "yes",
    kidsarea: "yes",
    neighbourhood: {},
    adress: {},
    website: {},
    imgLocation: ""
  },
  {
    imgLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: "",
    duration: "",
    courses: {},
    wellnes: {},
    cardio: {},
    strength: {},
    ladyarea: "yes",
    kidsarea: "yes",
    neighbourhood: {},
    adress: {},
    website: {},
    imgLocation: ""
  },
  {
    imgLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: "",
    duration: "",
    courses: {},
    wellnes: {},
    cardio: {},
    strength: {},
    ladyarea: "yes",
    kidsarea: "yes",
    neighbourhood: {},
    adress: {},
    website: {},
    imgLocation: ""
  },
  {
    imgLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: "",
    duration: "",
    courses: {},
    wellnes: {},
    cardio: {},
    strength: {},
    ladyarea: "yes",
    kidsarea: "yes",
    neighbourhood: {},
    adress: {},
    website: {},
    imgLocation: ""
  },
  {
    imgLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: "",
    duration: "",
    courses: {},
    wellnes: {},
    cardio: {},
    strength: {},
    ladyarea: "yes",
    kidsarea: "yes",
    neighbourhood: {},
    adress: {},
    website: {},
    imgLocation: ""
  },
  {
    imgLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: "",
    duration: "",
    courses: {},
    wellnes: {},
    cardio: {},
    strength: {},
    ladyarea: "yes",
    kidsarea: "yes",
    neighbourhood: {},
    adress: {},
    website: {},
    imgLocation: ""
  },
  {
    imgLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: "",
    duration: "",
    courses: {},
    wellnes: {},
    cardio: {},
    strength: {},
    ladyarea: "yes",
    kidsarea: "yes",
    neighbourhood: {},
    adress: {},
    website: {},
    imgLocation: ""
  }
];
