export const studios = [
  {
    imageLogo: "src",
    imgDetail: "src",
    name: "Fittness First Eherenfeld",
    price: ["40"],
    duration: ["24"],
    courses: ["Zumba", "Yoga", "Body-Pump"],
    wellness: ["Spa", "Sauna"],
    cardio: ["Rowing", "Stepper"],
    strength: ["Hanteln", "Geräte"],
    ladyarea: true,
    personaltraining: false,
    neighbourhood: "Ehrenfeld",
    adress: "Venloer Str. 389 50825 Köln",
    website: "https://www.fitnessfirst.de/clubs/koeln-ehrenfeld",
    imgLocation: "",
    city: "Köln"
  },
  {
    imageLogo: "src",
    imgDetail: "src",
    name: "FitnessLoft",
    price: [80, 30],
    duration: ["flex", "24"],
    courses: [
      "Yoga",
      "EDM",
      "Bodypump",
      "Bodyshape",
      "Boxen",
      "Bauch Beine Po"
    ],
    wellnes: ["Sauna"],
    cardio: ["Laufband", "Stepper", "Crosstrainer", "Fahrad-Ergometer"],
    strength: ["Kraftgeräte", "Hantelbereich"],
    ladyarea: true,
    personaltraining: true,
    neighbourhood: ["Altstadt-Nord"],
    adress: "Eigelstein 80-88 50668 Köln",
    website: "https://fitnessloft.de/fitnessstudios/koeln/",
    imgLocation: "src",
    city: "Köln"
  },
  {
    imageLogo: "src",
    imgDetail: "src",
    name: "Mc Fit Altstadt",
    price: ["19.90"],
    duration: ["24"],

    courses: ["CyberKurse", "Crossworkout", "Pre-Running", "Spinning"],
    wellnes: [],
    cardio: ["Stepper", "Rudern", "Crosstrainer"],
    strength: ["Hantelbereich", "Kraftgeräte", "Zirkeltraining"],
    ladyarea: true,
    personaltraining: false,
    neighbourhood: ["Innenstadt"],
    adress: "Hohe Str. 62-68 50667 Köln",
    website:
      "https://www.mcfit.com/de/studios/studiosuche/studiodetails/studio/koeln-altstadt/",
    imgLocation: "",
    city: "Köln"
  },
  {
    imageLogo: "src",
    imgDetail: "src",
    name: "Holmes Place am Gürzenich",
    price: ["89.90", "74.9", "64.9"],
    duration: ["flex", "12", "24"],
    courses: ["Yoga", "Bodypump", "Aerobic", "TaiChi", "Zumba", "Bodycombat"],
    wellnes: ["Pool", "Sauna", "Spa", "Solarium", "Massage"],
    cardio: [
      "Laufband",
      "Stepper",
      "Crosstrainer",
      "Fahrad-Ergometer",
      "Spinning-Bike",
      "Ruder-Ergometer"
    ],
    strength: ["Hantelbereich", "Zirkeltraining", "Kraftgeräte"],
    ladyarea: true,
    personaltraining: true,
    neighbourhood: ["Altstadt-Nord", "Innenstadt"],
    adress: "Gürzenichstraße 6 50667 Köln",
    website: "http://holmesplace.de/am-guerzenich.c/de/",
    imgLocation: "",
    city: "Köln"
  },
  {
    imageLogo: "src",
    imgDetail: "src",
    name: "Bushido Fitness",
    price: ["58", "53", "48"],
    duration: ["6", "12", "24"],
    courses: ["Bodypup", "Yin-Yoga", "Pilates", "RehaRüclen"],
    wellnes: ["Entspannungsraum", "Massagen", "Sauna"],
    cardio: ["Laufband", "Ruder-Ergometer", "Fahrradergometer"],
    strength: ["Hantelbereich", "Kraftgeräte", "Zirkeltraining"],
    ladyarea: false,
    personaltraining: false,
    neighbourhood: ["Innenstadt"],
    adress: "Mittelstraße 12, 50672 Köln",
    website: "https://www.bushido-fitness.de/",
    imgLocation: "",
    city: "Köln"
  },
  {
    imageLogo: "src",
    imgDetail: "src",
    name: "Art of Fitness",
    price: ["39.90", "29.90", "24.90"],
    duration: ["flex", "6", "12"],
    courses: ["Yoga", "Bodypump", "Aerobic", "TaiChi", "Zumba", "Bodycombat"],
    wellnes: ["Sauna", "Solarium", "Spa"],
    cardio: [
      "Laufband",
      "Stepper",
      "Crosstrainer",
      "Fahrad-Ergometer",
      "Spinning-Bike",
      "Ruder-Ergometer"
    ],
    strength: ["Hantelbereich", "Kraftgeräte", "Zirkeltraining"],
    ladyarea: true,
    personaltraining: true,
    neighbourhood: ["Ehrenfeld"],
    adress: "Maarweg 149-152 50825 Köln",
    website: "http://art-of-fitness.de/",
    imgLocation: "",
    city: "Köln"
  },

  {
    imageLogo: "src",
    imgDetail: "src",
    name: "Fittness First-Innenstadt",
    price: ["40"],
    duration: ["24"],

    courses: [
      "Zumba",
      "Yoga",
      "Body-Pump",
      "Tae Bo",
      "Energy Cycling",
      "Cardio-Step-Training"
    ],

    wellness: ["Spa", "Sauna", "Solarioum", "Massagen "],
    cardio: [
      "Laufband",
      "Stepper",
      "Crosstrainer",
      "Fahrad-Ergometer",
      "Spinning-Bike",
      "Ruder-Ergometer"
    ],
    strength: ["Hantelbereich", "Kraftgeräte"],
    ladyarea: true,
    personaltraining: true,
    neighbourhood: ["Innenstadt"],
    adress: "Schildergasse 94 50667 Köln",
    website: "http://www.fitnessfirst.de/clubs/koeln-innenstadt-schildergasse/",
    imgLocation: "",
    city: "Köln"
  },
  {
    imageLogo: "src",
    imgDetail: "src",
    name: "Just Fit 13",
    price: ["75", "55", "45"],
    duration: ["flex", "12", "24"],
    courses: [
      "Yoga",
      "Body-Pump",
      "Tae Bo",
      "Energy Cycling",
      "Cardio-Step-Training"
    ],
    wellnes: ["Spa", "Sauna", "Solarioum", "Massagen "],
    cardio: [
      "Laufband",
      "Stepper",
      "Crosstrainer",
      "Fahrad-Ergometer",
      "Spinning-Bike",
      "Ruder-Ergometer"
    ],
    strength: ["Hantelbereich", "Kraftgeräte", "Zirkeltraining"],
    ladyarea: true,
    personaltraining: true,
    neighbourhood: ["Altstadt-Süd"],
    adress: "Hohenstaufenring 30-32, 50674 Köln",
    website:
      "https://www.justfit-clubs.de/just-fit-13-city-koeln-altstadt-sued.html",
    imgLocation: "",
    city: "Köln"
  }
];
